[default_session]
startup_command = "~/.dotfiles/scripts/panes.sh"
disable_startup_command = true


[[session]]
name = "dotfiles"
path = "~/.dotfiles"
startup_command = "~/.dotfiles/scripts/split.sh 'nvim .' 'claude'"

[[session]]
name = "brew"
path = "~/.dotfiles"
startup_command = "~/.dotfiles/scripts/split.sh 'nvim brew/Brewfile.common' 'zsh'"

[[session]]
name = "nvim_plugins"
path = "~/.dotfiles/nvim/lua"
startup_command = "~/.dotfiles/scripts/split.sh 'nvim plugins.lua' 'claude'"

[[session]]
name = "obsidian_egradman"
path = "~/Documents/egradman/"
startup_command = "~/.dotfiles/scripts/obsidian_claude_split.sh"

[[session]]
name = "obsidian_red6"
path = "~/OneDrive - Red Six, Inc/red6/"
startup_command = "~/.dotfiles/scripts/obsidian_claude_split.sh"

[[session]]
name = "obsidian_shared"
path = "~/Documents/shared/"
startup_command = "~/.dotfiles/scripts/obsidian_claude_split.sh"

[[session]]
name = "dmz"
startup_command = '$HOME/.dotfiles/scripts/setup_ssh_pane.sh egradman@dmz.gradman.com'

[[session]]
name = "br"
startup_command = '$HOME/.dotfiles/scripts/setup_ssh_pane.sh bigred.red6ar.com'

[[session]]
name = "smo_aib"
startup_command = '$HOME/.dotfiles/scripts/setup_ssh_pane.sh rsadmi@10.1.11.74'

[[session]]
name = "mcp"
startup_command = 'vi /Users/egradman/Library/Application\ Support/Claude/claude_desktop_config.json'
