[server]
browser = "default"
follow_symlink = false

[keymap]
preset = "default"
destructive_delete = true

[keymap.overrides]

[runtime]
watcher_on_save = "lazy"
std_stream_max_bytes = 1000000
dotenv = []
output_max_bytes = 8000000
reactive_tests = true
on_cell_change = "autorun"
default_auto_download = []
auto_instantiate = true
default_sql_output = "auto"
auto_reload = "autorun"

[package_management]
manager = "uv"

[snippets]
include_default_snippets = true
custom_paths = []

[mcp]
presets = []

[mcp.mcpServers]

[experimental]

[language_servers.pylsp]
enable_pydocstyle = false
enable_ruff = true
enable_flake8 = false
enable_mypy = true
enabled = false
enable_pyflakes = false
enable_pylint = false

[save]
autosave_delay = 1000
format_on_save = false
autosave = "after_delay"

[diagnostics]
sql_linter = true

[display]
default_table_max_columns = 50
code_editor_font_size = 14
default_table_page_size = 10
default_width = "medium"
cell_output = "below"
theme = "light"
reference_highlighting = false
dataframes = "rich"

[ai]
mode = "manual"
rules = ""
inline_tooltip = false

[ai.anthropic]
api_key = "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"

[ai.models]
custom_models = []
chat_model = "anthropic/claude-opus-4-5"
displayed_models = ["anthropic/claude-opus-4-5"]
edit_model = "anthropic/claude-opus-4-5"

[formatting]
line_length = 79

[completion]
copilot = false
activate_on_typing = true
