oauth_token = "6oMTypOS3LdYiy2wMafI7gTlLRJcO6k1LYd-sSANm9Y.VxEc_bh7et0pt9mt4z4auBoQPJfe-Eu4wGBPMLqs8K4"
expiration_time = "2025-08-26T16:48:45.923Z"
refresh_token = "JjOkGS8rcEBFZBF6ZBDf-rFuV2lBwixgxZ77Zc4ghB8.maaQ7sgCaNoVsLLbSTs5FzIS4Q1yHWpjkoB22aYHtQ4"
scopes = [
  "account:read",
  "user:read",
  "workers:write",
  "workers_kv:write",
  "workers_routes:write",
  "workers_scripts:write",
  "workers_tail:read",
  "d1:write",
  "pages:write",
  "zone:read",
  "ssl_certs:write",
  "ai:write",
  "queues:write",
  "pipelines:write",
  "secrets_store:write",
  "containers:write",
  "cloudchamber:write",
  "offline_access"
]
